name: Auto merge Dependabot updates
on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable auto merge for Dependabot PRs
        if: github.actor == 'dependabot[bot]' && github.event.pull_request.draft == false
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}